name: tiktok_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.32.0
  firebase_auth: ^4.9.1
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.6.1
  video_player: ^2.8.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.0
  uuid: ^3.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
