// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW9L3IvM_ZL9ILqKVMOEswMBiok6jT8Vc',
    appId: '1:900740094951:web:350f29a8fba5aa84c6fb42',
    messagingSenderId: '900740094951',
    projectId: 'tiktok-clone-61b52',
    authDomain: 'tiktok-clone-61b52.firebaseapp.com',
    storageBucket: 'tiktok-clone-61b52.firebasestorage.app',
    measurementId: 'G-7TW2627EXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82R77qz5qSulcOyVOJomu2ZOUoAH1rnY',
    appId: '1:900740094951:android:d3ebd649262494cec6fb42',
    messagingSenderId: '900740094951',
    projectId: 'tiktok-clone-61b52',
    storageBucket: 'tiktok-clone-61b52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC98JGrTz9pYRDCQAkLOB7lCSIICt6eMmw',
    appId: '1:900740094951:ios:37f51442af5127eec6fb42',
    messagingSenderId: '900740094951',
    projectId: 'tiktok-clone-61b52',
    storageBucket: 'tiktok-clone-61b52.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC98JGrTz9pYRDCQAkLOB7lCSIICt6eMmw',
    appId: '1:900740094951:ios:37f51442af5127eec6fb42',
    messagingSenderId: '900740094951',
    projectId: 'tiktok-clone-61b52',
    storageBucket: 'tiktok-clone-61b52.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW9L3IvM_ZL9ILqKVMOEswMBiok6jT8Vc',
    appId: '1:900740094951:web:2fe4cd604dbe62b7c6fb42',
    messagingSenderId: '900740094951',
    projectId: 'tiktok-clone-61b52',
    authDomain: 'tiktok-clone-61b52.firebaseapp.com',
    storageBucket: 'tiktok-clone-61b52.firebasestorage.app',
    measurementId: 'G-DP89TEGXKZ',
  );

}